const BoardActionTypes = {
	BOARD_DATA_BRING : "BOARD_DATA_BRING",
	BOARD_DATA_BRING_FINISH : "BOARD_DATA_BRING_FINISH",
	BOARD_DATA_TO_RECENTLY : "BOARD_DATA_TO_RECENTLY",
	BOARD_DATA_TO_STAR : "BOARD_DATA_TO_STAR",
	ADD_LIST_ITEM: "ADD_LIST_ITEM",
	DEL_LIST_ITEM: "DEL_LIST_ITEM",
	CREATE_NEW_BOARD: "CREATE_NEW_BOARD",
	BOARD_DATA_TO_RECENTLY_START : "BOARD_DATA_TO_RECENTLY_START",
	BOARD_DATA_TO_STAR_START : "BOARD_DATA_TO_STAR_START",
	ADD_LIST_ITEM_START: "ADD_LIST_ITEM_START",
	DEL_LIST_ITEM_START: "DEL_LIST_ITEM_START",
	CREATE_NEW_BOARD_START: "CREATE_NEW_BOARD_START",
	ADD_LIST_START: "ADD_LIST_START",
	ADD_LIST: "ADD_LIST"
}

export default BoardActionTypes;